version: '3'

services:
  webapp:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    depends_on:
      - database

#  rest-api:
#    image: my-rest-api-image:latest  # Replace with the actual image for your REST API service
#    ports:
#      - "8080:8080"  # Map host port 8000 to container port 8000
#    depends_on:
#      - database  # Ensure that the REST API service starts after the database service

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: employees1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"  # Map host port 5432 to container port 5432
#    volumes:
#      - pgdata:/var/lib/postgresql/data  # Persist PostgreSQL data

#volumes:
#  pgdata:  # Define a named volume for PostgreSQL data
